name: DiscordPaperclip
version: ${version}
main: io.github.mccitiesclone.paperclip.DiscordPaperclipPlugin
description: Bidirectionally sync LuckPerms groups with Discord roles.
api-version: "1.21"
authors:
  - MCCitiesClone
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  paperclip.admin:
    description: Allows managing Discord Paperclip.
    default: op
  paperclip.link:
    description: Allows linking a Minecraft account to Discord.
    default: true
